# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /admin.apps.approved.list_get for http method type GET 
# RoostTestHash=d3180cece5
# 
# 

# ********RoostGPT********
Feature: Test the /api/admin.apps.approved.list endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test GET /api/admin.apps.approved.list with valid parameters
    Given path 'api/admin.apps.approved.list'
    And param token = <token>
    And param limit = <limit>
    And param cursor = <cursor>
    And param team_id = <team_id>
    And param enterprise_id = <enterprise_id>
    When method GET
    Then status 200
    And match response.ok == true
    And match response.approved_apps == '#[]'
    And match each response.approved_apps[*].app.id == '#string'
    And match each response.approved_apps[*].app.name == '#string'
    And match each response.approved_apps[*].app.is_app_directory_approved == '#boolean'
    And match each response.approved_apps[*].app.is_internal == '#boolean'
    And match each response.approved_apps[*].app.icons.image_32 == '#string'
    And match each response.approved_apps[*].app.icons.image_64 == '#string'
    And match each response.approved_apps[*].app.icons.image_128 == '#string'
    And match each response.approved_apps[*].app.icons.image_192 == '#string'
    And match each response.approved_apps[*].app.icons.image_512 == '#string'
    And match each response.approved_apps[*].app.icons.image_1024 == '#string'
    And match each response.approved_apps[*].app.icons.image_original == '#string'
    And match each response.approved_apps[*].scopes[*].name == '#string'
    And match each response.approved_apps[*].scopes[*].token_type == '#string'
    And match response.response_metadata.next_cursor == '#string'

    Examples:
      | read('admin.apps.approved.list_get.csv') |

  Scenario: Test GET /api/admin.apps.approved.list with invalid token
    Given path 'api/admin.apps.approved.list'
    And param token = '<invalid_token>'
    When method GET
    Then assert responseStatus != 200
    And match response.ok == false
    And match response.error == '#string'

  Scenario Outline: Test GET /api/admin.apps.approved.list with invalid parameters
    Given path 'api/admin.apps.approved.list'
    And param token = '<valid_token>'
    And param limit = <limit>
    When method GET
    Then assert responseStatus != 200
    And match response.ok == false
    And match response.error == '#string'

    Examples:
      | limit |
      |    -1 |
      |     0 |
      |  1001 |
