# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /admin.apps.approved.list_get for http method type GET 
# RoostTestHash=d3180cece5
# 
# 

# ********RoostGPT********
Feature: Testing the '/api/admin.apps.approved.list' API Endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Successful response for listing approved apps
    Given path 'api/admin.apps.approved.list'
    And param token = <token>
    And param limit = <limit>
    And param cursor = <cursor>
    And param team_id = <team_id>
    And param enterprise_id = <enterprise_id>
    When method GET
    Then status 200
    And match response.ok == true
    And match response.approved_apps == '#[]'
    And match each response.approved_apps[*].app.additional_info == '#string'
    And match each response.approved_apps[*].app.app_directory_url == '#string'
    And match each response.approved_apps[*].app.app_homepage_url == '#string'
    And match each response.approved_apps[*].app.description == '#string'
    And match each response.approved_apps[*].app.help_url == '#string'
    And match each response.approved_apps[*].app.icons.image_1024 == '#string'
    And match each response.approved_apps[*].app.icons.image_128 == '#string'
    And match each response.approved_apps[*].app.icons.image_192 == '#string'
    And match each response.approved_apps[*].app.id == '#string'
    And match each response.approved_apps[*].app.is_app_directory_approved == '#boolean'
    And match each response.approved_apps[*].app.is_internal == '#boolean'
    And match each response.approved_apps[*].app.name == '#string'
    And match each response.approved_apps[*].app.privacy_policy_url == '#string'
    And match each response.approved_apps[*].date_updated == '#number'
    And match each response.approved_apps[*].last_resolved_by.actor_id == '#string'
    And match each response.approved_apps[*].last_resolved_by.actor_type == '#string'
    And match each response.approved_apps[*].scopes[*].description == '#string'
    And match each response.approved_apps[*].scopes[*].is_sensitive == '#boolean'
    And match each response.approved_apps[*].scopes[*].name == '#string'
    And match each response.approved_apps[*].scopes[*].token_type == '#string'
    And match response.response_metadata.next_cursor == '#string'

    Examples:
      | read('admin.apps.approved.list_get.csv') |

  Scenario: Error response for invalid authentication
    Given path 'api/admin.apps.approved.list'
    And param token = 'invalid_token'
    When method GET
    Then status != 200
    And match response.ok == false
    And match response.error == 'invalid_auth'

  Scenario Outline: Invalid request parameters handling
    Given path 'api/admin.apps.approved.list'
    And param token = <token>
    And param limit = <limit>
    And param cursor = <cursor>
    And param team_id = <team_id>
    And param enterprise_id = <enterprise_id>
    When method GET
    Then status != 200
    And match response.ok == false
    And match response.error == 'invalid_argument'

    Examples:
      | token          | limit  | cursor | team_id  | enterprise_id  |
      | '<your_token>' | [2000] | ''     | ''       | ''             |
      | '<your_token>' | [-5]   | ''     | '<team>' | '<enterprise>' |
