# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
Feature: User Information API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario: Get current user information with API Key authentication
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)', Accept: 'application/json' }
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.login == '#string'
    And match response.name == '#string'

  Scenario: Get current user information with Basic authentication
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.login == '#string'
    And match response.name == '#string'

  Scenario: Get current user information with query parameter authentication
    * def authToken = karate.properties['circle-token']
    Given path '/me'
    And param circle-token = authToken
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.login == '#string'
    And match response.name == '#string'

  Scenario: Get current user information with invalid API Key authentication
    * configure headers = { Circle-Token: 'invalid-token', Accept: 'application/json' }
    Given path '/me'
    When method GET
    Then status != 200
    And match response.message == '#string'

  Scenario: Get current user information with invalid Basic authentication
    * def authHeader = 'Basic aW52YWxpZDppbnZhbGlk'
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/me'
    When method GET
    Then status != 200
    And match response.message == '#string'

  Scenario: Get current user information with invalid query parameter authentication
    Given path '/me'
    And param circle-token = 'invalid-token'
    When method GET
    Then status != 200
    And match response.message == '#string'

  Scenario: Get current user information without authentication
    Given path '/me'
    When method GET
    Then status != 200
    And match response.message == '#string'
