# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api_clone using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
Feature: User Information API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario: Get current user information - Success
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.login == '#string'
    And match response.name == '#string'
    And match karate.sizeOf(response) == 3

  Scenario: Get current user information - Verify required fields are present
    Given path '/me'
    When method GET
    Then status 200
    And match response contains { id: '#string', login: '#string', name: '#string' }
    And assert response.id != null
    And assert response.login != null
    And assert response.name != null

  Scenario: Get current user information - Verify UUID format for id field
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And assert response.id.length == 36
    And assert response.id.indexOf('-') != -1

  Scenario: Get current user information - Error response
    Given path '/me'
    When method GET
    Then assert responseStatus != 200
    And match response.message == '#string'
    And assert response.message != null

  Scenario: Get current user information - Verify response structure
    Given path '/me'
    When method GET
    Then status 200
    And match response ==
      """
      {
        "id": "#string",
        "login": "#string", 
        "name": "#string"
      }
      """
    And match response.id == '#notnull'
    And match response.login == '#notnull'
    And match response.name == '#notnull'
