# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /open-banking/v1.0/personal-mortgages_get for http method type GET 
# RoostTestHash=4b7d677b3c
# 
# 

# ********RoostGPT********
Feature: Personal Mortgages API

  Background:
    * def baseURL = karate.properties['MORTGAGE_LOANS_API_HOST'] || karate.properties['BASE_URL']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Validate Personal Mortgages API with valid headers
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = <ClientID>
    And header ClientSecret = <ClientSecret>
    And header Accept-Language = <Accept-Language>
    When method GET
    Then status 200
    And match response.meta.LastUpdated == '#string'
    And match response.meta.TotalResults == '#number'
    And match response.meta.Agreement == 'Use of the APIs and any related data will be subject to terms and conditions.'
    And match response.data == '#array'
    And match each response.data[*].Brand[*].BrandName == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].OnSaleIndicator == '#boolean'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.DefaultInterestRate == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].TierBandMethod == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].CustomerType == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].LoanInterestTierBand[*].TierValueMinimum == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].LoanInterestTierBand[*].TierValueMaximum == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].LoanInterestTierBand[*].CurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Repayment[*].MinimumRepaymentAmount == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Repayment[*].MinimumRepaymentAmountCurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.AgeEligibility.MinimumAge == '#number'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.IncomeEligibility.Amount == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.IncomeEligibility.AmountCurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.OtherEligibility[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.OtherEligibility[*].Description == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].FeaturesAndBenefits.FeatureBenefitItem[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].FeesCharges.FeeChargeDetail[*].FeeName == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].FeesCharges.FeeChargeDetail[*].FeeAmount == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].FeesCharges.FeeChargeDetail[*].FeeAmountCurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ProductDescription == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ProductURL == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.TcsAndCsURL == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ApplicationFormURL == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.SalesAccessChannels == '#array'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ServicingAccessChannels == '#array'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ApplicationHotline == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.CustomerServiceHotline == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].LoanCap[*].AssetType == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].LoanCap[*].LoanCapAmount == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].LoanCap[*].LoanCapAmountCurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].LoanCap[*].LoanToValueRatio == '#string'

    Examples:
      | read('open-banking_v1.0_personal-mortgages_get.csv') |

  Scenario: Validate Personal Mortgages API with missing ClientID
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientSecret = 'validClientSecret'
    When method GET
    Then status 400
    And match response.status == '400'
    And match response.title == 'Bad request'
    And match response.description == 'You have sent a request which could not be understood.'

  Scenario: Validate Personal Mortgages API with missing ClientSecret
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'validClientID'
    When method GET
    Then status 400
    And match response.status == '400'
    And match response.title == 'Bad request'
    And match response.description == 'You have sent a request which could not be understood.'

  Scenario: Validate Personal Mortgages API with unauthorized access
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'invalidClientID'
    And header ClientSecret = 'invalidClientSecret'
    When method GET
    Then status 401
    And match response.status == '401'
    And match response.title == 'Unauthorized Error'
    And match response.description == 'Your request could not be authenticated.'

  Scenario: Validate Personal Mortgages API with forbidden access
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'forbiddenClientID'
    And header ClientSecret = 'forbiddenClientSecret'
    When method GET
    Then status 403
    And match response.status == '403'
    And match response.title == 'Forbidden Error'
    And match response.description == 'You do not have proper authorization to access to the requested content.'

  Scenario: Validate Personal Mortgages API with client timeout
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'timeoutClientID'
    And header ClientSecret = 'timeoutClientSecret'
    When method GET
    Then status 408
    And match response.status == '408'
    And match response.title == 'Client timeout'
    And match response.description == 'Your client has failed to submit a request, and a timeout has occurred.'

  Scenario: Validate Personal Mortgages API with too many requests
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'rateLimitClientID'
    And header ClientSecret = 'rateLimitClientSecret'
    When method GET
    Then status 429
    And match response.status == '429'
    And match response.title == 'Too many requests'
    And match response.description == 'You have requested this resource too often. Slow down.'

  Scenario: Validate Personal Mortgages API with internal server error
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'serverErrorClientID'
    And header ClientSecret = 'serverErrorClientSecret'
    When method GET
    Then status 500
    And match response.status == '500'
    And match response.title == 'Internal server error'
    And match response.description == 'An error occurred on the server. No further information is available.'

  Scenario: Validate Personal Mortgages API with service temporarily unavailable
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = 'serviceUnavailableClientID'
    And header ClientSecret = 'serviceUnavailableClientSecret'
    When method GET
    Then status 503
    And match response.status == '503'
    And match response.title == 'Service temporarily unavailable'
    And match response.description == 'The service is temporarily unavailable.'
