# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /open-banking/v1.0/personal-mortgages_get for http method type GET 
# RoostTestHash=4b7d677b3c
# 
# 

# ********RoostGPT********
Feature: Personal Mortgages API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate GET /sandbox/open-banking/v1.0/personal-mortgages with valid headers
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = <ClientID>
    And header ClientSecret = <ClientSecret>
    And header Accept-Language = <Accept-Language>
    When method GET
    Then status 200
    And match response.meta.LastUpdated == '#string'
    And match response.meta.TotalResults == '#number'
    And match response.meta.Agreement == 'Use of the APIs and any related data will be subject to terms and conditions.'
    And match response.data == '#array'
    And match each response.data[*].Brand[*].BrandName == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].OnSaleIndicator == '#boolean'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.DefaultInterestRate == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].TierBandMethod == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].CustomerType == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].LoanInterestTierBand[*].TierValueMinimum == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].MortgageMarketingState[*].LoanInterest.LoanInterestTierBandSet[*].LoanInterestTierBand[*].CurrencyCode == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Repayment[*].MinimumRepaymentAmount == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].Eligibility.AgeEligibility.MinimumAge == '#number'
    And match each response.data[*].Brand[*].Mortgage[*].FeaturesAndBenefits.FeatureBenefitItem[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].FeesCharges.FeeChargeDetail[*].FeeName == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ProductDescription == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].LoanCap[*].AssetType == '#string'

    Examples:
      | read('open-banking_v1.0_personal-mortgages_get.csv') |

  Scenario Outline: Validate error responses for GET /sandbox/open-banking/v1.0/personal-mortgages
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And header ClientID = <ClientID>
    And header ClientSecret = <ClientSecret>
    And header Accept-Language = <Accept-Language>
    When method GET
    Then assert responseStatus != 200
    And match response.status == <status>
    And match response.title == <title>
    And match response.description == <description>

    Examples:
      | ClientID          | ClientSecret          | Accept-Language | status | title                | description                                              |
      | 'invalidClientID' | 'validClientSecret'   | 'en-HK'         | '401'  | 'Unauthorized Error' | 'Your request could not be authenticated.'               |
      | 'validClientID'   | 'invalidClientSecret' | 'en-HK'         | '401'  | 'Unauthorized Error' | 'Your request could not be authenticated.'               |
      | 'validClientID'   | 'validClientSecret'   | 'invalid'       | '400'  | 'Bad request'        | 'You have sent a request which could not be understood.' |
