# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /open-banking/v1.0/personal-mortgages_get for http method type GET 
# RoostTestHash=4b7d677b3c
# 
# 

# ********RoostGPT********
Feature: Verify Personal Mortgages API

  Background:
    """
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { 'Accept': 'application/json' }
    * def validClientID = 'valid-client-id'
    * def validClientSecret = 'valid-client-secret'
    """

  Scenario Outline: Fetch Personal Mortgages with valid headers
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And headers 
    """
    {
      "ClientID": "<ClientID>",
      "ClientSecret": "<ClientSecret>",
      "Accept-Language": <AcceptLanguage>
    }
    """
    When method GET
    Then match response.meta.LastUpdated == '#? _ == null || /[\\dT:+-]+/'
    And match response.meta.TotalResults == '#number'
    And match response.meta.Agreement == 'Use of the APIs and any related data will be subject to terms and conditions.'
    And match response.data == '#[]'
    And match each response.data[*].Brand == '#[]'
    And match each response.data[*].Brand[*].BrandName == '#string'
    And match each response.data[*].Brand[*].Mortgage == '#[]'
    And match each response.data[*].Brand[*].Mortgage[*].Name == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ProductDescription == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ProductURL == '#string'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.SalesAccessChannels == '#[]'
    And match each response.data[*].Brand[*].Mortgage[*].CoreProduct.ServicingAccessChannels == '#[]'
    Examples:
      | ClientID           | ClientSecret         | AcceptLanguage       |
      | 'valid-client-id'  | 'valid-client-secret'| ['\'en-HK\'']        |
      | 'valid-client-id'  | 'valid-client-secret'| ['\'zh-HK\'']        |
      | 'valid-client-id'  | 'valid-client-secret'| ['\'zh-CN\'']        |

  Scenario: Verify error response for unauthorized access
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And headers 
    """
    {
      "ClientID": "invalid-client-id",
      "ClientSecret": "invalid-client-secret"
    }
    """
    When method GET
    Then status 401
    And match response.status == '401'
    And match response.title == 'Unauthorized Error'
    And match response.description == 'Your request could not be authenticated.'

  Scenario Outline: Verify response for invalid headers
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And headers 
    """
    {
      "ClientID": "<ClientID>",
      "ClientSecret": "<ClientSecret>"
    }
    """
    When method GET
    Then status <statusCode>
    And match response.status == '<status>'
    And match response.title == '<title>'
    And match response.description == '<description>'
    Examples:
      | ClientID                | ClientSecret            | statusCode | status | title                 | description                                               |
      | ['\'invalid-client-id\''] | ['\'valid-client-secret\''] | 401       | '401'  | 'Unauthorized Error'  | 'Your request could not be authenticated.'                |
      | ['\'valid-client-id\'']   | ['\'invalid-client-secret\''] | 401       | '401'  | 'Unauthorized Error'  | 'Your request could not be authenticated.'                |
      | ['\'\'']                  | ['\'\'']                 | 400       | '400'  | 'Bad request'         | 'You have sent a request which could not be understood.' |
      | ['\'valid-client-id\'']   | ['\'valid-client-secret\''] | 429       | '429'  | 'Too many requests'   | 'You have requested this resource too often. Slow down.' |

  Scenario: Verify timeout error response
    Given path 'sandbox/open-banking/v1.0/personal-mortgages'
    And headers 
    """
    {
      "ClientID": "valid-client-id",
      "ClientSecret": "valid-client-secret"
    }
    """
    And karate.configure('timeout', 1)
    When method GET
    Then status 408
    And match response.status == '408'
    And match response.title == 'Client timeout'
    And match response.description == 'Your client has failed to submit a request, and a timeout has occurred.'
