# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1909018834
# 
# 

# ********RoostGPT********
Feature: Delete Pet API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Delete a pet with valid petId
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then status 200
    And match response == null

    Examples:
      | read('pet_petId_delete.csv') |

  Scenario Outline: Delete a pet with invalid petId
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then status 400
    And match response.error == '#string'

    Examples:
      | petId | api_key    |
      |    -1 | 'validKey' |
      |     0 | 'validKey' |

  Scenario Outline: Delete a pet with missing api_key
    Given path 'pet', <petId>
    When method DELETE
    Then assert responseStatus != 200
    And match response.error == '#string'

    Examples:
      | petId |
      |   123 |
      |   456 |

  Scenario: Delete a pet with unexpected error
    Given path 'pet', 789
    And header api_key = 'validKey'
    When method DELETE
    Then assert responseStatus != 200
    And match response.error == '#string'
