# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1909018834
# 
# 

# ********RoostGPT********
Feature: Delete Pet API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Delete a pet with valid petId
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then status 200
    And match response == null

    Examples:
      | read('pet_petId_delete.csv') |

  Scenario Outline: Delete a pet with invalid petId
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then status 400
    And match response.error == '#string'

    Examples:
      | petId | api_key |
      |    -1 | 'key1'  |
      |     0 | 'key2'  |

  Scenario Outline: Delete a pet with unexpected error
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then assert responseStatus != 200
    And match response.error == '#string'

    Examples:
      | petId | api_key |
      | 99999 | 'key1'  |
      | 88888 | 'key2'  |
