# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_put for http method type PUT 
# RoostTestHash=42edb35103
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['BASE_URL']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update an existing pet
    Given path 'pet'
    And request
      """
      {
        "id": <id>,
        "name": '<name>',
        "category": {
          "id": <categoryId>,
          "name": '<categoryName>'
        },
        "photoUrls": <photoUrls>,
        "tags": <tags>,
        "status": '<status>'
      }
      """
    When method PUT
    Then status 200
    And match response.id == <id>
    And match response.name == '<name>'
    And match response.category.id == <categoryId>
    And match response.category.name == '<categoryName>'
    And match response.photoUrls == <photoUrls>
    And match response.tags == <tags>
    And match response.status == '<status>'

    Examples:
      | read('pet_put.csv') |

  Scenario: Invalid ID supplied
    Given path 'pet'
    And request
      """
      {
        "id": -1,
        "name": 'invalid',
        "photoUrls": ['url'],
        "tags": [],
        "status": 'available'
      }
      """
    When method PUT
    Then status 400
    And match response.error == 'Invalid ID supplied'

  Scenario: Pet not found
    Given path 'pet'
    And request
      """
      {
        "id": 9999,
        "name": 'ghost',
        "photoUrls": ['url'],
        "tags": [],
        "status": 'available'
      }
      """
    When method PUT
    Then status 404
    And match response.error == 'Pet not found'

  Scenario: Validation exception
    Given path 'pet'
    And request
      """
      {
        "name": '',
        "photoUrls": [],
        "tags": [],
        "status": 'unknown'
      }
      """
    When method PUT
    Then status 422
    And match response.error == 'Validation exception'
