# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=946f2905a0
# 
# 

# ********RoostGPT********
Feature: Find Pets by Status

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Find pets by valid status
    Given path 'pet', 'findByStatus'
    And param status = <status>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].category.id == '##number'
    And match each response[*].category.name == '##string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].tags == '##[]'
    And match each response[*].status == '#string'

    Examples:
      | read('pet_findByStatus_get.csv') |

  Scenario: Find pets by invalid status
    Given path 'pet', 'findByStatus'
    And param status = 'invalidStatus'
    When method GET
    Then status 404

  Scenario: Find pets without status parameter
    Given path 'pet', 'findByStatus'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].category.id == '##number'
    And match each response[*].category.name == '##string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].tags == '##[]'
    And match each response[*].status == '#string'
