# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=b47488422d
# 
# 

# ********RoostGPT********
Feature: Test API Endpoint /pet/findByTags

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Find pets by tags with valid input
    Given path 'pet', 'findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].category.id == '#number'
    And match each response[*].category.name == '#string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].photoUrls[*] == '#string'
    And match each response[*].tags == '#[]'
    And match each response[*].tags[*].id == '#number'
    And match each response[*].tags[*].name == '#string'
    And match each response[*].status == '#string'

    Examples:
      | read('pet_findByTags_get.csv') |

  Scenario: Find pets by tags with invalid input
    Given path 'pet', 'findByTags'
    And param tags = ['invalidTag']
    When method GET
    Then status 404

  Scenario: Find pets by tags with no tags
    Given path 'pet', 'findByTags'
    When method GET
    Then status 200
    And match response == '#[]'

  Scenario: Find pets by tags with unexpected error
    Given path 'pet', 'findByTags'
    And param tags = ['unexpected']
    When method GET
    Then status 500
