# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=30359d59f9
# 
# 

# ********RoostGPT********
Feature: Update Pet with Form Data

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update pet with valid data
    Given path 'pet', <petId>
    And param name = <name>
    And param status = <status>
    When method POST
    Then status 200
    And match response == {}
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[] string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#string'

    Examples:
      | read('pet_petId_post.csv') |

  Scenario: Update pet with invalid data
    Given path 'pet', 9999
    And param name = 'InvalidName'
    And param status = 'unknown'
    When method POST
    Then status 400

  Scenario: Update pet with missing required fields
    Given path 'pet', 1
    When method POST
    Then status 400
