# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1909018834
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['BASE_URL']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Delete a pet
    Given path 'pet', <petId>
    And header api_key = <api_key>
    When method DELETE
    Then assert responseStatus == <expectedStatus>
    And match response == <expectedResponse>

    Examples:
      | petId | api_key | expectedStatus | expectedResponse                                           |
      |     1 | 'key1'  |            200 | {}                                                         |
      | 99999 | 'key2'  |            400 | """ { error: { code: '#number', message: '#string' } } """ |
      |     0 | 'key3'  |            400 | """ { error: { code: '#number', message: '#string' } } """ |

  Scenario: Delete a pet with missing authorization
    Given path 'pet', 1
    When method DELETE
    Then assert responseStatus != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'
