# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=68c053e0a8
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Add a new pet to the store with valid data
    Given path 'pet'
    And request
      """
      {
        "id": <id>,
        "name": '<name>',
        "category": {
          "id": <categoryId>,
          "name": '<categoryName>'
        },
        "photoUrls": <photoUrls>,
        "tags": <tags>,
        "status": '<status>'
      }
      """
    When method POST
    Then status 200
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[] string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#string'

    Examples:
      | read('pet_post.csv') |

  Scenario: Add a new pet with invalid input
    Given path 'pet'
    And request
      """
      {
        "name": '',
        "photoUrls": []
      }
      """
    When method POST
    Then status 400

  Scenario: Add a new pet with validation exception
    Given path 'pet'
    And request
      """
      {
        "name": 'doggie',
        "photoUrls": ['https://example.com/photo'],
        "status": 'invalid_status'
      }
      """
    When method POST
    Then status 422

  Scenario: Add a new pet with unexpected error
    Given path 'pet'
    And request
      """
      {
        "name": 'doggie',
        "photoUrls": ['https://example.com/photo'],
        "category": {
          "id": 1,
          "name": 'Dogs'
        },
        "tags": [{'id': 1, 'name': 'tag1'}],
        "status": 'available'
      }
      """
    When method POST
    Then assert responseStatus != 200
