# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=b47488422d
# 
# 

# ********RoostGPT********
Feature: Find Pets by Tags

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['BASE_URL']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Find pets by tags with valid inputs
    Given path 'pet', 'findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].category.id == '#number'
    And match each response[*].category.name == '#string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].tags == '#[]'
    And match each response[*].status == '#string'

    Examples:
      | read('pet_findByTags_get.csv') |

  Scenario: Find pets by tags with invalid input
    Given path 'pet', 'findByTags'
    And param tags = 'invalid_tag'
    When method GET
    Then status 400
    And match response.error == '#string'

  Scenario: Find pets by tags with unexpected error
    Given path 'pet', 'findByTags'
    And param tags = 'unexpected_error'
    When method GET
    Then assert responseStatus != 200
    And match response.error == '#string'
