# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=30359d59f9
# 
# 

# ********RoostGPT********
Feature: Update Pet with Form Data

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Update pet with valid form data
    Given path 'pet', <petId>
    And param name = <name>
    And param status = <status>
    When method POST
    Then status 200
    And match response ==
      """
      {
        id: '#number',
        name: '#string',
        category: '#? _ == null || typeof _ == "object"',
        photoUrls: '#array',
        tags: '#? _ == null || typeof _ == "array"',
        status: '#string'
      }
      """
    And match response.category.id == '##number'
    And match response.category.name == '##string'
    And match each response.photoUrls[*] == '#string'
    And match each response.tags[*].id == '##number'
    And match each response.tags[*].name == '##string'

    Examples:
      | read('pet_petId_post.csv') |

  Scenario: Update pet with invalid input
    Given path 'pet', 0
    When method POST
    Then assert responseStatus != 200

  Scenario: Unexpected error
    Given path 'pet', 999999
    When method POST
    Then assert responseStatus != 200
