# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=68c053e0a8
# 
# 

# ********RoostGPT********
Feature: Add a new pet to the store

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate successful creation of a new pet (200 OK response)
    Given path 'pet'
    And request
      """
      {
        "id": <id>,
        "name": <name>,
        "category": {
          "id": <category_id>,
          "name": <category_name>
        },
        "photoUrls": <photoUrls>,
        "tags": [
          {
            "id": <tag_id>,
            "name": <tag_name>
          }
        ],
        "status": <status>
      }
      """
    When method POST
    Then status 200
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[]string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#? _ == "available" || _ == "pending" || _ == "sold"'

    Examples:
      | read('pet_post.csv') |

  Scenario: Validate invalid input for creation (400 Bad Request)
    Given path 'pet'
    And request
      """
      {
        "name": null,
        "category": {
          "id": null,
          "name": null
        },
        "photoUrls": null,
        "tags": null,
        "status": null
      }
      """
    When method POST
    Then status 400
    And match response.error.description == '#string'

  Scenario: Validate validation exception (422 Unprocessable Entity)
    Given path 'pet'
    And request
      """
      {
        "id": "invalid",
        "name": "123",
        "category": {
          "id": "invalid",
          "name": "123"
        },
        "photoUrls": ["123"],
        "tags": [
          {
            "id": "invalid",
            "name": "123"
          }
        ],
        "status": "other"
      }
      """
    When method POST
    Then status 422
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Handle unexpected error response (default error response)
    Given path 'pet'
    And request
      """
      {
        "name": "test",
        "photoUrls": ["test-url"],
        "status": "invalid-status"
      }
      """
    When method POST
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'
