# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
Feature: Upload Image for Pet

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Upload image with valid petId and image
    Given path 'pet', <petId>, 'uploadImage'
    And param additionalMetadata = <additionalMetadata>
    And request
      """
      <imageBinary>
      """
    When method POST
    Then status 200
    And match response == { code: '#number', type: '#string', message: '#string' }

    Examples:
      | read('pet_petId_uploadImage_post.csv') |

  Scenario: Upload image with missing file
    Given path 'pet', 123, 'uploadImage'
    When method POST
    Then status 400
    And match response == null

  Scenario: Upload image for non-existent pet
    Given path 'pet', 999999, 'uploadImage'
    And request
      """
      'binaryData'
      """
    When method POST
    Then status 404
    And match response == null

  Scenario: Unexpected error during image upload
    Given path 'pet', 123, 'uploadImage'
    And request
      """
      'binaryData'
      """
    When method POST
    Then assert responseStatus != 200
    And match response == null
