# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=b47488422d
# 
# 

# ********RoostGPT********
Feature: Find pets by tags
  Description: Test the /pet/findByTags endpoint to ensure it behaves as expected and validates response schemas accurately.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate 200 successful operation response with valid tags
    Given path 'pet/findByTags'
    And param tags = <tags>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '##number'
    And match each response[*].name == '#string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].photoUrls[*] == '#string'
    And match each response[*].category == '##object'
    And match each response[*].category.id == '##number'
    And match each response[*].category.name == '##string'
    And match each response[*].tags == '##array'
    And match each response[*].tags[*].id == '##number'
    And match each response[*].tags[*].name == '##string'
    And match each response[*].status == '#? _ == "available" || _ == "pending" || _ == "sold" || _ == null'

    Examples:
      | read('pet_findByTags_get.csv') |

  Scenario Outline: Validate 400 Invalid tag value response
    Given path 'pet/findByTags'
    And param tags = <tags>
    When method GET
    Then status 400
    And match response.message == '#string'
    And match response.error == '##object'
    And match response.error.code == '##number'
    And match response.error.message == '##string'

    Examples:
      | tags              |
      | ['invalidTag']    |
      | ['123', 'abcd']   |
      | ['!@#$%', '&*()'] |

  Scenario Outline: Validate default unexpected error response
    Given path 'pet/findByTags'
    And param tags = <tags>
    When method GET
    Then assert responseStatus > 299
    And match response == '##object'
    And match response.error == '##object'
    And match response.error.code == '##number'
    And match response.error.message == '##string'

    Examples:
      | tags               |
      | ['']               |
      | ['unsupportedTag'] |
