# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
Feature: Upload Image for Pet

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Upload image with valid petId and image
    Given path 'pet', <petId>, 'uploadImage'
    And param additionalMetadata = <additionalMetadata>
    And request """
      <imageContent>
    """
    When method POST
    Then status 200
    And match response == { code: '#number', type: '#string', message: '#string' }

    Examples:
      | petId | additionalMetadata | imageContent          |
      | 1     | 'metadata1'        | 'binaryImageContent1' |
      | 2     | 'metadata2'        | 'binaryImageContent2' |

  Scenario: Upload image with missing file
    Given path 'pet', 1, 'uploadImage'
    And param additionalMetadata = 'metadata1'
    When method POST
    Then status 400
    And match response == null

  Scenario: Upload image for non-existent pet
    Given path 'pet', 9999, 'uploadImage'
    And param additionalMetadata = 'metadata1'
    And request """
      binaryImageContent
    """
    When method POST
    Then status 404
    And match response == null

  Scenario: Upload image with unexpected error
    Given path 'pet', 1, 'uploadImage'
    And param additionalMetadata = 'metadata1'
    And request """
      binaryImageContent
    """
    When method POST
    Then assert responseStatus != 200
    And match response == null
