# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_post for http method type POST 
# RoostTestHash=68c053e0a8
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Add a new pet to the store with valid data
    Given path '/pet'
    And request
      """
      {
        "id": <id>,
        "name": <name>,
        "category": {
          "id": <categoryId>,
          "name": <categoryName>
        },
        "photoUrls": <photoUrls>,
        "tags": <tags>,
        "status": <status>
      }
      """
    When method POST
    Then status 200
    And match response.id == '#number'
    And match response.name == <name>
    And match response.category.id == '#number'
    And match response.category.name == <categoryName>
    And match response.photoUrls == <photoUrls>
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == <status>

    Examples:
      | read('pet_post.csv') |

  Scenario: Add a new pet to the store with invalid input
    Given path '/pet'
    And request
      """
      {
        "name": "",
        "photoUrls": []
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Add a new pet to the store with validation exception
    Given path '/pet'
    And request
      """
      {
        "name": "doggie",
        "photoUrls": ["https://example.com/dog"],
        "status": "invalid_status"
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Add a new pet to the store with unexpected error
    Given path '/pet'
    And request
      """
      {
        "name": "doggie",
        "photoUrls": ["https://example.com/dog"]
      }
      """
    When method POST
    Then assert responseStatus != 200
