# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
Feature: Pet API Tests

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase

  Scenario Outline: Get Pet by ID with API Key Authorization
    Given path 'pet', <petId>
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    When method GET
    Then status <statusCode>
    And match responseHeaders['Content-Type'] contains 'application/json'
    And match response != null
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[] string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#string'

    Examples:
      | petId | statusCode |
      |     1 |        200 |
      | 99999 |        404 |
      |    -1 |        400 |

  Scenario Outline: Get Pet by ID with OAuth2 Authorization
    Given path 'pet', <petId>
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status <statusCode>
    And match responseHeaders['Content-Type'] contains 'application/json'
    And match response != null
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[] string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#string'

    Examples:
      | petId | statusCode |
      |     1 |        200 |
      | 99999 |        404 |
      |    -1 |        400 |

  Scenario: Get Pet by ID with Invalid ID
    Given path 'pet', 'invalid'
    * def authToken = karate.properties['api_key']
    * configure headers = { api_key: '#(authToken)' }
    When method GET
    Then status != 200
    And match response.error == '#string'
