# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
Feature: Validate Get Pet by ID Endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { 'Accept': 'application/json' }

  Scenario Outline: Validate successful responses for Get Pet by ID
    Given path 'pet/<petId>'
    When method GET
    Then status 200
    And match response.id == <expectedPetId>
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == """
    [
      '#string'
    ]
    """
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status in ['available', 'pending', 'sold']

    Examples:
      | petId | expectedPetId |
      |  10   |     10        |
      |   5   |      5        |

  Scenario: Validate invalid ID supplied error
    Given path 'pet/invalidId'
    When method GET
    Then status 400
    And match response.error == '#string'
    And match responseStatus != 200

  Scenario: Validate pet not found error
    Given path 'pet/9999'
    When method GET
    Then status 404
    And match response.error == '#string'
    And match responseStatus != 200

  Scenario: Validate unexpected error response
    Given path 'pet/-1'
    When method GET
    Then status '#number'
    And match response.error.code == '#number'
    And match response.error.message == '#string'
    And match responseStatus != 200
