# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=30359d59f9
# 
# 

# ********RoostGPT********
Feature: Update Pet with Form Data

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update pet with valid form data
    Given path 'pet', <petId>
    And param name = <name>
    And param status = <status>
    When method POST
    Then status 200
    And match response == {}
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.photoUrls == '#[] string'
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '#string'

    Examples:
      | read('pet_petId_post.csv') |

  Scenario: Update pet with invalid input
    Given path 'pet', 0
    When method POST
    Then assert responseStatus != 200
    And match response.error == {}
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Handle unexpected error
    Given path 'pet', 999999
    When method POST
    Then assert responseStatus != 200
    And match response.error == {}
    And match response.error.code == '#number'
    And match response.error.message == '#string'
