# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_put for http method type PUT 
# RoostTestHash=42edb35103
# 
# 

# ********RoostGPT********
Feature: Update an existing pet

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Update pet with valid data
    Given path 'pet'
    And request
      """
      {
        "id": <id>,
        "name": '<name>',
        "category": {
          "id": <categoryId>,
          "name": '<categoryName>'
        },
        "photoUrls": <photoUrls>,
        "tags": <tags>,
        "status": '<status>'
      }
      """
    When method PUT
    Then status 200
    And match response.id == <id>
    And match response.name == '<name>'
    And match response.category.id == <categoryId>
    And match response.category.name == '<categoryName>'
    And match response.photoUrls == <photoUrls>
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '<status>'

    Examples:
      | read('pet_put.csv') |

  Scenario: Update pet with invalid ID
    Given path 'pet'
    And request
      """
      {
        "id": -1,
        "name": 'invalid',
        "photoUrls": ['http://example.com/photo']
      }
      """
    When method PUT
    Then assert responseStatus != 200

  Scenario: Update pet not found
    Given path 'pet'
    And request
      """
      {
        "id": 9999,
        "name": 'ghost',
        "photoUrls": ['http://example.com/photo']
      }
      """
    When method PUT
    Then assert responseStatus != 200

  Scenario: Update pet with validation exception
    Given path 'pet'
    And request
      """
      {
        "name": '',
        "photoUrls": []
      }
      """
    When method PUT
    Then assert responseStatus != 200
