# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet_put for http method type PUT 
# RoostTestHash=42edb35103
# 
# 

# ********RoostGPT********
Feature: Update an existing pet

  Background:
    * def baseURL = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update pet with valid data
    Given path 'pet'
    And request
      """
      {
        "id": <id>,
        "name": '<name>',
        "category": {
          "id": <categoryId>,
          "name": '<categoryName>'
        },
        "photoUrls": <photoUrls>,
        "tags": <tags>,
        "status": '<status>'
      }
      """
    When method PUT
    Then status 200
    And match response.id == <id>
    And match response.name == '<name>'
    And match response.category.id == <categoryId>
    And match response.category.name == '<categoryName>'
    And match response.photoUrls == <photoUrls>
    And match each response.tags[*].id == '#number'
    And match each response.tags[*].name == '#string'
    And match response.status == '<status>'

    Examples:
      | read('pet_put.csv') |

  Scenario: Update pet with invalid ID
    Given path 'pet'
    And request
      """
      {
        "id": -1,
        "name": 'invalid',
        "photoUrls": ['http://example.com/invalid']
      }
      """
    When method PUT
    Then status 404
    And match response.error == 'Pet not found'

  Scenario: Update pet not found
    Given path 'pet'
    And request
      """
      {
        "id": 9999,
        "name": 'notfound',
        "photoUrls": ['http://example.com/notfound']
      }
      """
    When method PUT
    Then status 404
    And match response.error == 'Pet not found'

  Scenario: Update pet with validation exception
    Given path 'pet'
    And request
      """
      {
        "name": '',
        "photoUrls": []
      }
      """
    When method PUT
    Then status 422
    And match response.error == 'Validation exception'

  Scenario: Update pet with unexpected error
    Given path 'pet'
    And request
      """
      {
        "id": 10,
        "name": 'unexpected',
        "photoUrls": ['http://example.com/unexpected']
      }
      """
    When method PUT
    Then assert responseStatus != 200
    And match response.error == 'Unexpected error'
