# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
Feature: Pet Image Upload API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Upload pet image with valid inputs
    Given path 'pet', <petId>, 'uploadImage'
    And param additionalMetadata = <additionalMetadata>
    And request """
      <image>
    """
    When method POST
    Then status 200
    And match response == { code: '#number', type: '#string', message: '#string' }

    Examples:
      | petId | additionalMetadata | image          |
      | 1     | 'metadata1'        | 'sampleImage1' |
      | 2     | 'metadata2'        | 'sampleImage2' |

  Scenario Outline: Upload pet image without file
    Given path 'pet', <petId>, 'uploadImage'
    And param additionalMetadata = <additionalMetadata>
    And request ''
    When method POST
    Then status 400
    And match response == null

    Examples:
      | petId | additionalMetadata |
      | 1     | 'metadata1'        |
      | 2     | 'metadata2'        |

  Scenario Outline: Upload pet image for non-existent pet
    Given path 'pet', <petId>, 'uploadImage'
    And param additionalMetadata = <additionalMetadata>
    And request """
      <image>
    """
    When method POST
    Then status 404
    And match response == null

    Examples:
      | petId | additionalMetadata | image          |
      | 9999  | 'metadata1'        | 'sampleImage1' |
      | 8888  | 'metadata2'        | 'sampleImage2' |

  Scenario: Handle unexpected error during image upload
    Given path 'pet', 1, 'uploadImage'
    And param additionalMetadata = 'metadata1'
    And request """
      'sampleImage1'
    """
    When method POST
    Then assert responseStatus != 200
    And match response == null
