# ********RoostGPT********

# Test generated by RoostGPT for test swagger2 using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=946f2905a0
# 
# 

# ********RoostGPT********
Feature: Find Pets by Status API

  Background:
    * def urlBase = karate.properties['SWAGGER_PETSTORE_OPENAPI_30_API_HOST'] || karate.properties['BASE_URL']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate successful response for finding pets by status
    Given path 'pet', 'findByStatus'
    And param status = <status>
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].category.id == '##number'
    And match each response[*].category.name == '##string'
    And match each response[*].photoUrls == '#[]'
    And match each response[*].photoUrls[*] == '#string'
    And match each response[*].tags == '##[]'
    And match each response[*].tags[*].id == '##number'
    And match each response[*].tags[*].name == '##string'
    And match each response[*].status == '#string'

    Examples:
      | read('pet_findByStatus_get.csv') |

  Scenario: Validate response for invalid status value
    Given path 'pet', 'findByStatus'
    And param status = 'invalidStatus'
    When method GET
    Then status 400

  Scenario: Validate default error response
    Given path 'pet', 'findByStatus'
    And param status = ''
    When method GET
    Then assert responseStatus != 200
